package encore.matching;

public enum PolishCompanyType {
	SPÓ£KA_AKCYJNA, 
	SPÓ£KA_Z_OGRANICZON¥_ODPOWIEDZIALNOŒCI¥, 
	SPÓ£KA_JAWNA, 
	SPÓ£KA_PARTNERSKA, 
	SPÓ£KA_KOMANDYTOWA, 
	SPÓ£KA_KOMANDYTOWO_AKCYJNA,
	SPÓ£KA_CYWILNA,
	SPÓ£DZIELNIA,
	FUNDACJA,
	STOWARZYSZENIE,
	PRZEDSIÊBIOSTWO_PAÑSTWOWE,
	DZIA£ALNOŒÆ_GOSPODARCZA,
	SPÓ£KA_EUROPEJSKA,
	SPÓ£DZIELNIA_EUROPEJSKA,
	EUROPEJSKIE_ZGRUPOWANIE_INTERESÓW_GOSPODARCZYCH,
	PRZEDSIÊBIORSTWO_ZBIOROWEGO_INWESTOWANIA_W_ZBYWALNE_PAPIERY_WARTOŒCIOWE,
	SPÓ£KA_WODNA,
	INNA,
	BRAK_INFORMACJI
}
